# encoding: utf-8

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 1048
    v.cpus = 1
    v.name = "easyrtc"
  end

  config.vm.box = "ubuntu/trusty64"
  config.ssh.forward_agent = true

  config.vm.network :forwarded_port, guest: 47121 , host: 47121

  config.vm.synced_folder '../..', '/home/vagrant/app', owner: 'vagrant', mount_options: ['dmode=775','fmode=775']

  config.vm.provision 'shell', path: 'bootstrap.sh'

end